version: '3'
services:
  node:
    container_name: node
    restart: always
    build: ./node-backend
    ports:
      - '5200:5200'
    #  Hier stelltst du schon eine Vebrindung zwischen den beiden Containern her ;)
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # den Port musst du und solltest du nicht exposen
    #ports:
    #  - '27017:27017'
  angular:
    container_name: angular
    build: ./angular-frontend
    #  wir verwenden ja jetzt nginx zum ausliefern der App
    # der hört standardmäßig auf Port 80 ;)
    ports:
      - '80:80'
    links:
      - mongo
