export let institutes = [
    "Institut für Analytische Chemie",
    "Institut für Anorganische Chemie - Center of Nanobionics and Photochemical Sciences (CNPS)",
    "Institut für Chemie der Polymere",
    "Intitut für Chemische Technologie Anorganischer Stoffe",
    "Institut für Chemische Technologie Organischer Stoffe",
    "Institut für Katalyse",
    "Institut für Organische Chemie",
    "Institut für Physikalische Chemie",
    "Institut für Polymer Extrusion and Compounding",
    "Institut für Polymeric Materials and Testing",
    "Institut für Polymer Injection Moulding and Process Automation",
    "Institut für Polymer Product Engineering",
    "Institut für Polymerwissenschaften",
    "Institut für Verfahrenstechnik",
    "Linzer Institut für Organische Solarzellen (LIOS)",
    "Institut für Anwendungsorientierte Wissensverarbeitung",
    "Institut für Computational Perception",
    "Institut für Complex Systems",
    "Institut für Computergrafik",
    "Institut für Formale Modelle und Verifikation",
    "Institut für Integrierte Schaltungen",
    "Institut für Machine Learning",
    "Institut für Netzwerke und Sicherheit",
    "Institut für Pervasive Computing",
    "Institut für Signalverarbeitung",
    "Institut für Software Systems Engineering",
    "Institut für Symbolic Artificial Intelligence",
    "Institut für Systemsoftware",
    "Institut für Telekooperation",
    "Doktoratskolleg Computational Mathematics",
    "Institut für Algebra",
    "Institut für Analysis",
    "Institut für Angewandte Geometrie",
    "Institut für Finanzmathematik und Angewandte Zahlentheorie",
    "Institut für Industriemathematik",
    "Institut für Numerische Mathematik",
    "Institut für Stochastik",
    "Institut für Symbolisches Rechnen (RISC)",
    "Institut für Wissensbasierte Mathematische Systeme",
    "Institut für Design und Regelung Mechatronischer Systeme",
    "Institut für Elektrische Antriebe und Leistungselektronik",
    "Institut für Elektrische Messtechnik",
    "Institut für Konstruktiven Leichtbau",
    "Institut für Maschinenlehre und Hydraulische Antriebstechnik",
    "Institut für Mechatronische Produktentwicklung und Fertigung",
    "Institut für Medizin- und Biomechatronik",
    "Institut für Metallische Konstruktionswerkstoffe",
    "Institut für Mikroelektronik und Mikrosensorik",
    "Institut für Nachrichtentechnik und Hochfrequenzsysteme",
    "Institut für Regelungstechnik und Prozessautomatisierung",
    "Institut für Robotik",
    "Institut für Strömungslehre und Wärmeübertragung",
    "Institut für Technische Mechanik",
    "JKU HOERBIGER Research Institute for Smart Actuators",
    "Institut für Angewandte Physik",
    "Institut für Biophysik",
    "Institut für Experimentalphysik",
    "Institut für Halbleiter- und Festkörperphysik",
    "Institut für Theoretische Physik",
    "Zentrum für Oberflächen- und Nanoanalytik (ZONA)",
    "Institut für Betriebliche Finanzwirtschaft",
    "Institut für Betriebliche und regionale Umweltwirtschaft",
    "Institut für Betriebswirtschaftliche Steuerlehre",
    "Institut für Controlling und Consulting",
    "Institut für Digital Business",
    "Institut für Handel, Absatz und Marketing",
    "Institut für Innovationsmanagement",
    "Institut für Internationales Management",
    "Institut für Management Accounting",
    "Institut für Organisation",
    "Institut für Personalführung und Veränderungsmanagement",
    "Institut für Produktions- und Logistikmanagement",
    "Institut für Public und Nonprofit Management",
    "Institut für Strategisches Management",
    "Institut für Unternehmensgründung und Unternehmensentwicklung",
    "Institut für Unternehmensrechnung und Wirtschaftsprüfung",
    "Institut für Wirtschaftsinformatik - Communications Engineering",
    "Institut für Wirtschaftsinformatik - Data & Knowledge Engineering",
    "Institut für Wirtschaftsinformatik - Information Engineering",
    "Institut für Wirtschaftsinformatik - Software Engineering",
    "Institut für Angewandte Statistik",
    "Institut für Volkswirtschaftslehre",
    "Institut für Gesellschafts- und Sozialpolitik",
    "Institut für Neuere Geschichte und Zeitgeschichte",
    "Institut für Philosophie und Wissenschaftstheorie",
    "Institut für Sozial- und Wirtschaftsgeschichte",
    "Institut für Soziologie",
    "Institut für Pädagogik und Psychologie",
    "Institut für Wirtschafts- und Berufspädagogik",
    "Center of Health Care Research",
    "Forschungsinstitut für Bankwesen",
    "Forschungsinstitut für die Gesamtanalyse der Wirtschaft",
    "Institut für Kulturwirtschaft und Kulturforschung",
    "Kompetenzzentrum Wissensmanagement",
    "Institut für Römisches Recht",
    "Institut für Zivilrecht",
    "Multimediale Linzer Rechtsstudien",
    "Institut für Multimediales Öffentliches Recht",
    "Institut für Staatsrecht und Politische Wissenschaften",
    "Institut für Universitätsrecht",
    "Institut für Verwaltungsrecht und Verwaltungslehre",
    "Forschungsinstitut für Steuerrecht und Steuermanagement",
    "Institut für Arbeits- und Sozialrecht",
    "Institut für Europarecht",
    "Institut für Finanzrecht, Steuerrecht und Steuerpolitik",
    "Institut für Recht der sozialen Daseinsvorsorge und Medizinrecht",
    "Institut für Unternehmensrecht",
    "Institut für Völkerrecht, Luftfahrtrecht und Internationale Beziehungen",
    "Institut für Zivilprozessrecht, Insolvenzrecht und Vergleichendes Prozessrecht",
    "Institut für Europäisches und Österreichisches Zivilverfahrensrecht",
    "Institut für Kanonistik, Europäische Rechtsgeschichte und Religionsrecht",
    "Institut für Legal Gender Studies",
    "Institut für Strafrechtswissenschaften",
    "Institut für Umweltrecht",
    "Universitätsklinik für Anästhesiologie und operative Intensivmedizin",
    "Universitätsklinik für Augenheilkunde und Optometrie",
    "Universitätsklinik für Gynäkologie, Geburtshilfe und Gynäkologische Endokrinologie",
    "Universitätsklinik für Hals-, Nasen- und Ohrenheilkunde",
    "Universitätsklinik für Hämatologie und internistische Onkologie",
    "Universitätsklinik für Herz-, Gefäß- und Thoraxchirurgie",
    "Universitätsklinik für Innere Medizin mit Schwerpunkt Gastroenterologie / Hepatologie",
    "Universitätsklinik für Kinder- und Jugendheilkunde",
    "Universitätsklinik für Neurochirurgie",
    "Universitätsklinik für Orthopädie und Traumatologie",
    "Institut für Anatomie und Zellbiologie",
    "Institut für Pharmakologie",
    "Institut für Physiologie und Pathophysiologie",
    "Klinisches Institut für Pathologie und Molekularpathologie",
    "Forschungsinstitut für Entwicklungsmedizin",
    "Business School - Divison für Finance & Accounting",
    "Business School - Divison für Management & Marketing",
    "Business School - Divison für Supply Chain & Information Management",
    "LIT Artificial Intelligence Lab",
    "LIT Cyber-Physical Systems Lab",
    "LIT Law Lab",
    "LIT Secure and Correct Systems Lab",
    "LIT Medical Engineering Lab",
    "LIT Robopsychology Lab",
    "LIT Soft Materials Lab",
    "Linz School of Education - Abteilung für Bildungsforschung",
    "Linz School of Education - Abteilung für Didaktik der Mathematik, Informatik, Naturwissenschaften und Technik (MINT)",
    "Institut für Frauen- und Geschlechterforschung",
    "Institut für Integrierte Qualitätsgestaltung",
    "Institut Integriert Studieren",
    "Zentrum für Fachsprachen und Interkulturelle Kommunikation",
    "Zentrum für Kriminologie"
];